import { StyleSheet, Platform } from "react-native";

export const fontFamily = Platform.select({
  ios: "Plus Jakarta Sans",
  android: "sans-serif",
  default: "sans-serif",
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  scrollBody: {
    padding: 16,
    paddingBottom: 24,
  },

  // 1. Top Summary Hero Card
  topHeroCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.06)",
    marginBottom: 16,
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
    gap: 10,
  },
  heroTopContent: {
    flex: 1,
    justifyContent: "center",
  },
  badgesCluster: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
  },
  publishedDateRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 5,
  },
  publishedDateText: {
    fontFamily,
    fontSize: 11,
    fontWeight: "500",
    color: "#64748b",
  },
  editedLabelText: {
    fontFamily,
    fontSize: 10.5,
    color: "#94a3b8",
    fontStyle: "italic",
    fontWeight: "500",
  },
  typeIconBox: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  typeBadgePill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 9999,
  },
  typeBadgeText: {
    fontFamily,
    fontSize: 12,
    fontWeight: "700",
  },
  methodBadgePill: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 9999,
  },
  methodBadgePillHand: {
    backgroundColor: "#fef3c7",
  },
  methodBadgePillOnline: {
    backgroundColor: "#e0f2fe",
  },
  methodBadgeText: {
    fontFamily,
    fontSize: 11,
    fontWeight: "700",
  },
  policyBadgePillSmall: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 3.5,
    borderRadius: 9999,
  },
  policyBadgePillLateSmall: {
    backgroundColor: "#f0fdfa",
    borderWidth: 1,
    borderColor: "#99f6e4",
  },
  policyBadgePillStrictSmall: {
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  policyBadgeTextSmall: {
    fontFamily,
    fontSize: 10,
    fontWeight: "700",
  },
  heroTitleText: {
    fontFamily,
    fontSize: 18,
    fontWeight: "800",
    color: "#0f172a",
    lineHeight: 24,
    marginBottom: 10,
  },
  heroMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  metaLabelText: {
    fontFamily,
    fontSize: 12.5,
    fontWeight: "600",
    color: "#64748b",
  },
  metaValueText: {
    fontFamily,
    fontSize: 12.5,
    fontWeight: "700",
    color: "#0f172a",
  },
  metaDivider: {
    fontFamily,
    fontSize: 12.5,
    fontWeight: "600",
    color: "#cbd5e1",
  },

  // Grade & Feedback Box inside Card
  gradeFeedbackBox: {
    backgroundColor: "#faf5ff",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: "#e9d5ff",
    marginBottom: 10,
  },
  gradeHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  gradeIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#f3e8ff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  gradeScoreCol: {
    flex: 1,
  },
  gradeScoreLabel: {
    fontFamily,
    fontSize: 10,
    fontWeight: "800",
    color: "#7e22ce",
    letterSpacing: 0.5,
    marginBottom: 1,
  },
  gradeScoreValue: {
    fontFamily,
    fontSize: 16,
    fontWeight: "800",
    color: "#581c87",
  },
  gradeTotalText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#7e22ce",
  },
  gradeLateText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#b45309",
  },
  feedbackContainer: {
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(126, 34, 206, 0.12)",
  },
  feedbackHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  feedbackLabel: {
    fontFamily,
    fontSize: 11,
    fontWeight: "700",
    color: "#6b21a8",
  },
  feedbackBody: {
    fontFamily,
    fontSize: 12.5,
    color: "#3b0764",
    lineHeight: 18,
  },

  // Instructions inside Card
  instructionsContainer: {
    backgroundColor: "#f8fafc",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.04)",
    marginBottom: 10,
  },
  instructionsHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  instructionsHeading: {
    fontFamily,
    fontSize: 12,
    fontWeight: "700",
    color: "#334155",
  },
  instructionsBody: {
    fontFamily,
    fontSize: 12.5,
    color: "#475569",
    lineHeight: 18,
  },

  // Resources inside Card
  resourcesBox: {
    backgroundColor: "#f8fafc",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.04)",
  },
  resourcesHeadingRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  resourcesHeadingText: {
    fontFamily,
    fontSize: 12,
    fontWeight: "700",
    color: "#334155",
  },
  resourceItemPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.06)",
    marginBottom: 6,
  },
  resourceItemIcon: {
    width: 28,
    height: 28,
    borderRadius: 7,
    backgroundColor: "#eff6ff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  resourceItemDetails: {
    flex: 1,
  },
  resourceItemName: {
    fontFamily,
    fontSize: 12.5,
    fontWeight: "600",
    color: "#0f172a",
  },
  resourceItemMeta: {
    fontFamily,
    fontSize: 10.5,
    color: "#64748b",
  },

  // 2. Resources Wrapper
  resourcesWrapper: {
    marginBottom: 16,
  },

  // 3. Existing Submission Card
  mySubmissionCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.06)",
    marginBottom: 16,
  },
  subStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f0fdf4",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    alignSelf: "flex-start",
  },
  subStatusBadgeText: {
    fontFamily,
    fontSize: 12.5,
    fontWeight: "700",
    color: "#15803d",
  },
  feedbackBanner: {
    marginTop: 10,
    backgroundColor: "#f8fafc",
    padding: 10,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#2563eb",
  },
  feedbackBannerTitle: {
    fontFamily,
    fontSize: 11,
    fontWeight: "700",
    color: "#2563eb",
    marginBottom: 2,
  },
  feedbackBannerText: {
    fontFamily,
    fontSize: 12,
    color: "#334155",
    lineHeight: 16,
  },
  closedSubmissionLockNotice: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fef2f2",
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.15)",
  },
  closedSubmissionLockText: {
    fontFamily,
    fontSize: 11.5,
    fontWeight: "600",
    color: "#b91c1c",
  },

  // 4. Overdue / Late Status Banners
  closedNoticeBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#fef2f2",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(220, 38, 38, 0.2)",
    marginBottom: 16,
  },
  closedIconBox: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#fee2e2",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    marginTop: 1,
  },
  lateNoticeBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#fffbeb",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(217, 119, 6, 0.25)",
    marginBottom: 16,
  },
  lateIconBox: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#fef3c7",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    marginTop: 1,
  },
  bannerTextCol: {
    flex: 1,
  },
  closedBannerTitle: {
    fontFamily,
    fontSize: 13.5,
    fontWeight: "800",
    color: "#b91c1c",
    marginBottom: 3,
  },
  closedBannerDesc: {
    fontFamily,
    fontSize: 11.5,
    color: "#991b1b",
    lineHeight: 16,
  },
  lateBannerTitle: {
    fontFamily,
    fontSize: 13.5,
    fontWeight: "800",
    color: "#b45309",
    marginBottom: 3,
  },
  lateBannerDesc: {
    fontFamily,
    fontSize: 11.5,
    color: "#92400e",
    lineHeight: 16,
  },

  // 5. Closed Empty State Card
  closedEmptyCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.06)",
    marginTop: 4,
    marginBottom: 16,
  },
  closedLargeIconBox: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#fef2f2",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  closedEmptyTitle: {
    fontFamily,
    fontSize: 16,
    fontWeight: "800",
    color: "#0f172a",
    marginBottom: 6,
    textAlign: "center",
  },
  closedEmptyDesc: {
    fontFamily,
    fontSize: 12.5,
    color: "#64748b",
    textAlign: "center",
    lineHeight: 18,
  },

  // 6. Section Heading
  sectionHeading: {
    fontFamily,
    fontSize: 13,
    fontWeight: "800",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 10,
    marginTop: 4,
  },

  // 7. Radio Selector Group
  radioGroupCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.06)",
    marginBottom: 20,
    overflow: "hidden",
  },
  radioOptionRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#cbd5e1",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  radioOuterSelected: {
    borderColor: "#2563eb",
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#2563eb",
  },
  radioTextCol: {
    flex: 1,
  },
  radioTitle: {
    fontFamily,
    fontSize: 14,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 2,
  },
  radioSubtitle: {
    fontFamily,
    fontSize: 11.5,
    color: "#64748b",
  },
  radioDivider: {
    height: 1,
    backgroundColor: "rgba(15, 23, 42, 0.06)",
    marginLeft: 46,
  },

  // 8. Add Submission Section (Online)
  addSubmissionSection: {
    marginTop: 4,
  },
  actionButtonsRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
  },
  actionTabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eff6ff",
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: "rgba(37, 99, 235, 0.15)",
  },
  actionTabBtnActive: {
    backgroundColor: "#dbeafe",
    borderColor: "#2563eb",
  },
  actionTabBtnText: {
    fontFamily,
    fontSize: 12,
    fontWeight: "700",
    color: "#2563eb",
  },

  // 9. Inline Drawers
  drawerCard: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(37, 99, 235, 0.2)",
    marginBottom: 16,
    shadowColor: "#2563eb",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  drawerTitle: {
    fontFamily,
    fontSize: 13,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 10,
  },
  drawerInput: {
    fontFamily,
    fontSize: 13,
    color: "#0f172a",
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.1)",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  drawerActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
    marginTop: 12,
  },
  drawerCancelBtn: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: "#f1f5f9",
  },
  drawerCancelText: {
    fontFamily,
    fontSize: 12,
    fontWeight: "600",
    color: "#64748b",
  },
  drawerSaveBtn: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: "#2563eb",
  },
  drawerSaveText: {
    fontFamily,
    fontSize: 12,
    fontWeight: "700",
    color: "#ffffff",
  },

  // 10. Attached Items List
  itemCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.06)",
    marginBottom: 8,
  },
  fileIconBox: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: "#eff6ff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  fileInfoCol: {
    flex: 1,
    marginRight: 8,
  },
  fileNameText: {
    fontFamily,
    fontSize: 13,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 2,
  },
  fileSizeText: {
    fontFamily,
    fontSize: 11,
    color: "#64748b",
  },
  removeBtn: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: "#f1f5f9",
  },

  // 11. Helper Text
  helperTextContainer: {
    marginTop: 8,
    paddingHorizontal: 4,
  },
  helperText: {
    fontFamily,
    fontSize: 11,
    color: "#94a3b8",
    lineHeight: 16,
  },

  // 12. Offline Mode Card
  offlineNoticeCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.06)",
    alignItems: "center",
    marginTop: 8,
  },
  offlineIconBox: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  offlineTitle: {
    fontFamily,
    fontSize: 15,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 6,
  },
  offlineDesc: {
    fontFamily,
    fontSize: 12.5,
    color: "#64748b",
    textAlign: "center",
    lineHeight: 18,
  },

  // 13. Fixed Bottom Bar
  fixedBottomBar: {
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderTopColor: "rgba(15, 23, 42, 0.06)",
    paddingHorizontal: 16,
    paddingTop: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 8,
  },
  submitButton: {
    backgroundColor: "#0f172a",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  submitButtonClosed: {
    backgroundColor: "#94a3b8",
  },
  submitButtonLate: {
    backgroundColor: "#d97706",
  },
  submitButtonDisabled: {
    opacity: 0.5,
  },
  submitButtonText: {
    fontFamily,
    fontSize: 14,
    fontWeight: "700",
    color: "#ffffff",
  },
  buttonInnerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
});
